# path
output_path: "/home/v-xinyanfan/2021/WSDM/result"
dataset_path: "/home/v-xinyanfan/2021/WSDM/dataset"

# general
gpu_id: 0
use_gpu: True
seed: 2020
state: INFO
dataset_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True

# training settings
epochs: 200
batch_size: 4096
learning_rate: 0.01

learner: adam
eval_step: 1
stopping_step: 5
clip_grad_norm: ~
weight_decay: 0.0

# dataset
neg_items_num: 4

# mode
use_extractor: False
add_bias_to: 'user_emb'
stage: 'train-on-sub'
